name: Build RK Kernel

on: 
  workflow_dispatch:
  push:
     branches: ["rk"]
     paths:
        - '.github/workflows/build-rk.yml'
        - '.github/workflows/rk-aosp.yml'
        - '.github/workflows/rk-miui.yml'
  
jobs:
  build-apollo-miui-kernel:
    uses: ./.github/workflows/rk-miui.yml
    with:
      IS_RELEASE: true
      DEVICE_CODE: 'apollo'
      USE_KERNELSU: true
